### ISSUE TITLE
Error While building with Dockerfile (open3D)

### ISSUE THREAD

**Issue by ZorAttC** [Kin-Zhang/vdbfusion_mapping#4]
When I Install Open3D dependencies,   "util/install_deps_ubuntu.sh" doesn't to assume yes to apt-get,which results in Abort.As I am a freshman to Docker,I don't know how to solve this problem.

**Comment by Kin-Zhang** [comment]
Ha I see, I didn't have such problem don't know why, but you can just echo/print yes before `|`, Here is an example:

```bash
printf "y\ny\ny\n\n" | bash -c "$(curl -fsSL https://raw.githubusercontent.com/Kin-Zhang/Kin-Zhang/main/scripts/setup_ohmyzsh.sh)"

```

**Comment by ZorAttC** [comment]
Thank you so much！
